--
-- File generated with SQLiteStudio v3.4.4 on seg mar 11 10:01:56 2024
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: CUSTOMERS
CREATE TABLE IF NOT EXISTS CUSTOMERS (CUSTOMERNUMBER, CUSTOMERNAME, PHONE, CITY, STATE, POSTALCODE, COUNTRY);

-- Table: DIM_TIME
CREATE TABLE IF NOT EXISTS DIM_TIME (TIME_ID, MONTH_ID, YEAR_ID);

-- Table: FACT
CREATE TABLE IF NOT EXISTS FACT (ID, ORDERNUMBER, CUSTOMERNUMBER, PRODUCTCODE, TIME_ID, SALES, QUANTITY);

-- Table: ORDERS
CREATE TABLE IF NOT EXISTS ORDERS (ORDERNUMBER, ORDERDATE, REQUIREDDATE, SHIPPEDDATE, STATUS, CUSTOMERNUMBER);

-- Table: PRODUCTS
CREATE TABLE IF NOT EXISTS PRODUCTS (PRODUCTCODE, PRODUCTNAME, PRODUCTLINE, PRODUCTSCALE, PRODUCTVENDOR, QUANTITYINSTOCK, BUYPRICE, MSRP);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
